name: TwitchBattleAPI
version: '1.0.0'
main: org.emrage.twitchbattleapi.TwitchBattleAPI
api-version: '1.21'
authors: [ TwitchBattle ]
commands:
  team:
    description: Team management commands
    usage: /team <create|delete|add|remove|list|info>
    permission: twitchbattle.team
  points:
    description: Point system commands
    usage: /points <add|remove|set|get|reset|show>
    permission: twitchbattle.points

permissions:
  twitchbattle.team:
    description: Allows access to team commands
    default: op
  twitchbattle.points:
    description: Allows access to point commands
    default: op